### ISSUE TITLE
spelling of covariance

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/zodiax#32] opened 2023-09-13 04:41 UTC
https://github.com/LouisDesdoigts/zodiax/blob/4a15434e8c4fb5e7845a91c287b1aac0b0d799eb/zodiax/bayes.py#L67

best to get this right throughout the package!

**Comment by LouisDesdoigts** [comment] 2023-09-13 04:47
Duplicate of #30

**Closed by LouisDesdoigts** 2023-09-13 04:47 UTC
